#!/usr/bin/env tsx
/**
 * tenant:seed — regenerate `supabase/seed.sql` from the tenant configs.
 *
 * The generated seed contains ONLY demo data:
 *   * the studio configuration (through `publish_tenant_config`, so the seed
 *     exercises the same code path as a real publish);
 *   * two demo owner accounts and their memberships;
 *   * demo bookings and payments, every row marked `is_demo = true` and only
 *     inside `preview` tenants.
 *
 * A `live` tenant never receives demo rows, and because preview tenants do not
 * enqueue notifications, seeding cannot send anything to a real device.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { SUPABASE_DIR, ROOT } from '../lib/paths';
import { loadTenant, toPublishPayload } from '../lib/tenant-config';
import { resolveTargets, parseArgs } from '../lib/cli';

/** Fixed ids so the seed is reproducible and re-runnable. */
const DEMO_USERS = [
  {
    id: '00000000-0000-0000-0000-0000000000a1',
    email: 'owner@demo-a.invalid',
    password: 'demo-owner-password',
    displayName: 'Владелец (демо A)',
  },
  {
    id: '00000000-0000-0000-0000-0000000000b2',
    email: 'owner@demo-b.invalid',
    password: 'demo-owner-password',
    displayName: 'Владелец (демо B)',
  },
];

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJson(value: unknown): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

interface DemoTenant {
  slug: string;
  payload: ReturnType<typeof toPublishPayload>;
  serviceKeys: string[];
  resourceCount: number;
}

async function buildSeed(tenants: DemoTenant[]): Promise<string> {
  const lines: string[] = [];

  lines.push('-- =============================================================================');
  lines.push('-- Generated by `npm run tenant:seed`. Do not edit by hand.');
  lines.push('--');
  lines.push('-- Contains demo data only. Applied automatically by `supabase db reset`.');
  lines.push('-- =============================================================================');
  lines.push('');
  lines.push('begin;');
  lines.push('');
  lines.push('-- ---------------------------------------------------------------------------');
  lines.push('-- Demo owner accounts. Passwords are demo-only and are hashed with pgcrypto.');
  lines.push('-- ---------------------------------------------------------------------------');
  for (const user of DEMO_USERS) {
    lines.push(
      `insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)`,
    );
    lines.push(`values (`);
    lines.push(`  ${sqlString(user.id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',`);
    lines.push(`  ${sqlString(user.email)},`);
    lines.push(`  crypt(${sqlString(user.password)}, gen_salt('bf')),`);
    lines.push(`  now(),`);
    lines.push(`  '{"provider":"email","providers":["email"]}'::jsonb,`);
    lines.push(`  ${sqlJson({ display_name: user.displayName })}::jsonb,`);
    lines.push(`  now(), now()`);
    lines.push(`) on conflict (id) do nothing;`);
    lines.push('');
  }

  lines.push('-- ---------------------------------------------------------------------------');
  lines.push('-- Studio configuration, published through the same function a real publish uses.');
  lines.push('-- ---------------------------------------------------------------------------');
  for (const tenant of tenants) {
    lines.push(`-- ${tenant.slug}: ${tenant.serviceKeys.length} service(s), ${tenant.resourceCount} resource(s)`);
    lines.push(`select public.publish_tenant_config(${sqlJson(tenant.payload)}::jsonb);`);
    lines.push('');
  }

  lines.push('-- ---------------------------------------------------------------------------');
  lines.push('-- Owners. Membership is what grants access; there is no public signup.');
  lines.push('-- ---------------------------------------------------------------------------');
  tenants.forEach((tenant, index) => {
    const user = DEMO_USERS[index % DEMO_USERS.length];
    if (!user) return;
    lines.push(`insert into public.tenant_members (tenant_id, user_id, role, status, display_name)`);
    lines.push(`select t.id, ${sqlString(user.id)}, 'owner', 'active', ${sqlString(user.displayName)}`);
    lines.push(`from public.tenants t where t.slug = ${sqlString(tenant.slug)}`);
    lines.push(`on conflict (tenant_id, user_id) do update set role = 'owner', status = 'active';`);
    lines.push('');
  });

  lines.push('-- ---------------------------------------------------------------------------');
  lines.push('-- Demo bookings and payments. Only for preview tenants, always marked is_demo,');
  lines.push('-- never more than one per (tenant, resource, moment).');
  lines.push('-- ---------------------------------------------------------------------------');
  for (const tenant of tenants) {
    const serviceKey = tenant.serviceKeys[0];
    if (!serviceKey) continue;

    lines.push(`do $$`);
    lines.push(`declare`);
    lines.push(`  v_tenant uuid;`);
    lines.push(`  v_service record;`);
    lines.push(`  v_resource uuid;`);
    lines.push(`  v_customer uuid;`);
    lines.push(`  v_booking uuid;`);
    lines.push(`  v_starts timestamptz;`);
    lines.push(`  v_window tstzrange;`);
    lines.push(`  v_day date;`);
    lines.push(`  v_attempt integer := 0;`);
    lines.push(`begin`);
    lines.push(`  select id into v_tenant from public.tenants where slug = ${sqlString(tenant.slug)};`);
    lines.push(`  if v_tenant is null then return; end if;`);
    lines.push(`  -- demo rows are only ever written into a preview tenant`);
    lines.push(`  if (select status from public.tenants where id = v_tenant) <> 'preview' then return; end if;`);
    lines.push(`  if exists (select 1 from public.bookings where tenant_id = v_tenant and is_demo) then return; end if;`);
    lines.push('');
    lines.push(`  select s.id, s.duration_min, s.buffer_before_min, s.buffer_after_min, s.price_cents, s.currency`);
    lines.push(`    into v_service`);
    lines.push(`  from public.services s`);
    lines.push(`  where s.tenant_id = v_tenant and s.key = ${sqlString(serviceKey)} and s.is_active`);
    lines.push(`  limit 1;`);
    lines.push(`  if v_service.id is null then return; end if;`);
    lines.push('');
    lines.push(`  select r.id into v_resource`);
    lines.push(`  from public.resources r`);
    lines.push(`  where r.tenant_id = v_tenant and r.is_active`);
    lines.push(`  order by r.sort_order, r.key limit 1;`);
    lines.push(`  if v_resource is null then return; end if;`);
    lines.push('');
    lines.push(`  insert into public.customers (tenant_id, name, phone, phone_normalized, is_demo)`);
    lines.push(`  values (v_tenant, 'Демо-клиент', '+7 000 000-00-00', '70000000000', true)`);
    lines.push(`  on conflict (tenant_id, phone_normalized) do update set is_demo = true`);
    lines.push(`  returning id into v_customer;`);
    lines.push('');
    lines.push(`  -- find the first free slot in the next three weeks, walking the working windows`);
    lines.push(`  for v_day in select g::date from generate_series(`);
    lines.push(`      (now() at time zone app.tenant_timezone(v_tenant))::date + 1,`);
    lines.push(`      (now() at time zone app.tenant_timezone(v_tenant))::date + 21,`);
    lines.push(`      interval '1 day') as g`);
    lines.push(`  loop`);
    lines.push(`    exit when v_booking is not null;`);
    lines.push(`    for v_window in select * from app.working_windows(v_tenant, v_day) loop`);
    lines.push(`      exit when v_booking is not null;`);
    lines.push(`      v_starts := lower(v_window);`);
    lines.push(`      v_attempt := 0;`);
    lines.push(`      while v_starts < upper(v_window) and v_booking is null and v_attempt < 40 loop`);
    lines.push(`        v_attempt := v_attempt + 1;`);
    lines.push(`        begin`);
    lines.push(`          insert into public.bookings (`);
    lines.push(`            tenant_id, customer_id, service_id, resource_id, display_number,`);
    lines.push(`            price_cents, currency, duration_min, buffer_before_min, buffer_after_min,`);
    lines.push(`            service_name_snapshot, starts_at, ends_at, status, access_token_hash,`);
    lines.push(`            idempotency_hash, is_demo`);
    lines.push(`          )`);
    lines.push(`          select`);
    lines.push(`            v_tenant, v_customer, v_service.id, v_resource,`);
    lines.push(`            app.next_counter(v_tenant, 'booking'),`);
    lines.push(`            v_service.price_cents, v_service.currency, v_service.duration_min,`);
    lines.push(`            v_service.buffer_before_min, v_service.buffer_after_min,`);
    lines.push(`            (select s.name from public.services s where s.id = v_service.id),`);
    lines.push(`            v_starts, v_starts + make_interval(mins => v_service.duration_min),`);
    lines.push(`            'confirmed', digest('demo-seed-token:' || v_tenant::text || ':' || v_starts::text, 'sha256'),`);
    lines.push(`            digest('demo-seed:' || v_starts::text, 'sha256'), true`);
    lines.push(`          returning id into v_booking;`);
    lines.push('');
    lines.push(`          insert into public.resource_occupancies (tenant_id, resource_id, booking_id, kind, period)`);
    lines.push(`          select v_tenant, v_resource, v_booking, 'booking', b.occupancy`);
    lines.push(`          from public.bookings b where b.id = v_booking;`);
    lines.push(`        exception`);
    lines.push(`          when exclusion_violation or unique_violation then`);
    lines.push(`            v_booking := null;`);
    lines.push(`        end;`);
    lines.push(`        v_starts := v_starts + make_interval(mins => 30);`);
    lines.push(`      end loop;`);
    lines.push(`    end loop;`);
    lines.push(`  end loop;`);
    lines.push('');
    lines.push(`  if v_booking is not null then`);
    lines.push(`    insert into public.booking_events (tenant_id, booking_id, event, actor, payload)`);
    lines.push(`    values (v_tenant, v_booking, 'booking_created', 'system', '{"demo":true}'::jsonb);`);
    lines.push('');
    lines.push(`    insert into public.payments (tenant_id, booking_id, amount_cents, currency, method, status, paid_at, is_demo)`);
    lines.push(`    select v_tenant, v_booking, v_service.price_cents, v_service.currency, 'cash', 'paid', now(), true;`);
    lines.push(`  end if;`);
    lines.push(`end;`);
    lines.push(`$$;`);
    lines.push('');
  }

  lines.push('commit;');
  lines.push('');
  return lines.join('\n');
}

async function main(): Promise<void> {
  const args = parseArgs();
  const slugs = await resolveTargets(args);

  const tenants: DemoTenant[] = [];
  for (const slug of slugs) {
    const tenant = await loadTenant(slug);
    tenants.push({
      slug,
      payload: toPublishPayload(tenant),
      serviceKeys: tenant.config.services.map((service) => service.key),
      resourceCount: tenant.config.resources.length,
    });
  }

  const sql = await buildSeed(tenants);
  const target = path.join(SUPABASE_DIR, 'seed.sql');
  await mkdir(SUPABASE_DIR, { recursive: true });
  await writeFile(target, sql, 'utf8');

  console.log(`Wrote ${path.relative(ROOT, target)} (${tenants.length} tenant(s), ${sql.length} bytes)`);
  for (const tenant of tenants) {
    console.log(`  ${tenant.slug}: demo booking for service "${tenant.serviceKeys[0] ?? '—'}"`);
  }
}

await main().catch((error) => {
  console.error(error);
  process.exit(1);
});
