#!/usr/bin/env tsx
/**
 * tenant:publish — turn `tenants/<slug>/business.json` + images into:
 *
 *   1. static tenant artifacts under `public/s/<slug>/`
 *        manifest.webmanifest, config.json, assets/*
 *   2. a SQL statement file under `supabase/generated/` (always), and
 *   3. the live database (only when service-role credentials are present).
 *
 * Nothing here is specific to one studio: publishing a second studio adds a
 * second directory and never rewrites the first one.
 *
 *   npm run tenant:publish -- graphite-detailing
 *   npm run tenant:publish -- --all
 *   npm run tenant:publish -- --all --dry-run
 */
import { copyFile, mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { buildManifest, buildShellConfig } from '../lib/manifest';
import {
  GENERATED_SQL_DIR,
  PUBLIC_DIR,
  ROOT,
  tenantPublicDir,
  tenantPublicPath,
} from '../lib/paths';
import { loadTenant, toPublishPayload, type LoadedTenant } from '../lib/tenant-config';
import { fail, logSection, parseArgs, resolveTargets } from '../lib/cli';

interface PublishResult {
  slug: string;
  publicDir: string;
  copiedAssets: number;
  sqlFile: string;
  appliedToDatabase: boolean;
  databaseMessage: string;
}

function sqlLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function buildSql(payload: unknown): string {
  const json = JSON.stringify(payload);
  return `-- Generated by \`npm run tenant:publish\`. Do not edit by hand.
-- Apply with:  npx supabase db push   (or psql -f <this file>)
-- Publishing is idempotent: it upserts catalog rows, never deletes bookings,
-- and only replaces assets that the pipeline itself created.
select public.publish_tenant_config(${sqlLiteral(json)}::jsonb) as publish_result;
`;
}

/**
 * Copy every file from `tenants/<slug>/assets/`.
 *
 * The whole folder is copied rather than only the assets declared in the
 * config, so extra material (iOS startup images, an unused photo, a press kit)
 * is served too and a studio can reference it from the app without a config
 * change. Declared assets are the ones that also carry metadata into the
 * database and the manifest.
 */
async function copyTenantAssets(tenant: LoadedTenant, targetDir: string): Promise<number> {
  const assetsDir = path.join(targetDir, 'assets');
  await mkdir(assetsDir, { recursive: true });

  const sourceDir = path.join(tenant.dir, 'assets');
  let entries: string[];
  try {
    entries = await readdir(sourceDir);
  } catch {
    entries = [];
  }

  let copied = 0;
  for (const entry of entries) {
    const source = path.join(sourceDir, entry);
    const info = await stat(source);
    if (!info.isFile()) continue;
    await copyFile(source, path.join(assetsDir, entry));
    copied += 1;
  }

  return copied;
}

async function publishTenant(slug: string, dryRun: boolean): Promise<PublishResult> {
  const tenant = await loadTenant(slug);
  const targetDir = tenantPublicDir(slug);
  const publicPath = tenantPublicPath(slug);

  console.log(`→ ${slug}`);

  if (!dryRun) {
    // Start from a clean directory so a removed asset cannot linger.
    await rm(targetDir, { recursive: true, force: true });
  }
  await mkdir(targetDir, { recursive: true });

  const copiedAssets = dryRun ? tenant.assets.length : await copyTenantAssets(tenant, targetDir);

  const manifest = buildManifest(tenant.config, tenant.assets);
  const shellConfig = buildShellConfig(tenant.config, tenant.assets, tenant.hash);
  const payload = toPublishPayload(tenant);

  const sql = buildSql(payload);
  const sqlFile = path.join(GENERATED_SQL_DIR, `tenant_${slug}.sql`);

  if (!dryRun) {
    await writeFile(
      path.join(targetDir, 'manifest.webmanifest'),
      `${JSON.stringify(manifest, null, 2)}\n`,
      'utf8',
    );
    await writeFile(
      path.join(targetDir, 'config.json'),
      `${JSON.stringify(shellConfig, null, 2)}\n`,
      'utf8',
    );
    await writeFile(
      path.join(targetDir, 'published-config.json'),
      `${JSON.stringify(payload, null, 2)}\n`,
      'utf8',
    );

    await mkdir(GENERATED_SQL_DIR, { recursive: true });
    await writeFile(sqlFile, sql, 'utf8');
  }

  console.log(`  static   ${publicPath}/ (${copiedAssets} image asset(s))`);
  console.log(`  manifest id=${manifest.id} scope=${manifest.scope} icons=${manifest.icons.length}`);
  console.log(`  sql      ${path.relative(ROOT, sqlFile)}`);

  // ----- optional live apply ---------------------------------------------
  let appliedToDatabase = false;
  let databaseMessage = 'skipped: no Supabase credentials in the environment';

  const url = process.env.SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!dryRun && url && serviceKey) {
    try {
      const { createClient } = await import('@supabase/supabase-js');
      const client = createClient(url, serviceKey, {
        auth: { persistSession: false, autoRefreshToken: false },
      });
      const { data, error } = await client.rpc('publish_tenant_config', { p_config: payload });
      if (error) {
        appliedToDatabase = false;
        databaseMessage = `failed: ${error.message}`;
      } else {
        appliedToDatabase = true;
        databaseMessage = `applied: ${JSON.stringify(data)}`;
      }
    } catch (error) {
      databaseMessage = `failed: ${(error as Error).message}`;
    }
  } else if (!dryRun) {
    databaseMessage =
      'skipped: set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to apply the config, ' +
      `or run the generated file: supabase/generated/tenant_${slug}.sql`;
  }

  console.log(`  database ${databaseMessage}`);

  return { slug, publicDir: targetDir, copiedAssets, sqlFile, appliedToDatabase, databaseMessage };
}

/**
 * `public/tenants.json` lets the root screen list the studios without a
 * database round trip, while runtime data still comes from the database.
 */
async function writeTenantDirectory(tenants: Awaited<ReturnType<typeof loadTenant>>[]) {
  const directory = tenants
    .map((tenant) => ({
      slug: tenant.slug,
      name: tenant.config.name,
      tagline: tenant.config.tagline ?? null,
      accentColor: tenant.config.branding.accentColor,
      timezone: tenant.config.timezone,
      basePath: `${tenantPublicPath(tenant.slug)}/`,
      heroUrl: tenant.assets.find((asset) => asset.kind === 'hero')?.url ?? null,
      logoUrl: tenant.assets.find((asset) => asset.kind === 'logo')?.url ?? null,
      status: tenant.config.status,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  await mkdir(PUBLIC_DIR, { recursive: true });
  await writeFile(
    path.join(PUBLIC_DIR, 'tenants.json'),
    `${JSON.stringify(directory, null, 2)}\n`,
    'utf8',
  );

  return directory;
}

async function main(): Promise<void> {
  const args = parseArgs();
  const dryRun = args.flags.has('dry-run');
  const targets = await resolveTargets(args);

  if (targets.length === 0) {
    fail('No tenants found under tenants/*/business.json');
  }

  logSection(`Publishing ${targets.length} tenant(s)${dryRun ? ' (dry run)' : ''}`);

  const results: PublishResult[] = [];
  const loaded: Awaited<ReturnType<typeof loadTenant>>[] = [];

  for (const slug of targets) {
    try {
      results.push(await publishTenant(slug, dryRun));
      loaded.push(await loadTenant(slug));
    } catch (error) {
      fail(`publishing ${slug} failed: ${(error as Error).message}`);
    }
  }

  if (!dryRun) {
    const directory = await writeTenantDirectory(loaded);
    console.log(`\npublic/tenants.json lists ${directory.length} studio(s)`);
  }

  logSection('Summary');
  for (const result of results) {
    console.log(
      `${result.slug.padEnd(22)} assets=${String(result.copiedAssets).padStart(3)}  db=${result.appliedToDatabase ? 'applied' : 'not applied'}`,
    );
  }

  const notApplied = results.filter((result) => !result.appliedToDatabase);
  if (notApplied.length > 0 && !dryRun) {
    console.log(
      `\n${notApplied.length} tenant(s) were NOT applied to a database. ` +
        'This is expected without credentials — the generated SQL files are ready to apply.',
    );
  }
}

await main().catch((error) => {
  console.error(error);
  process.exit(1);
});
